apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kubeflow-manifests
  namespace: devops
spec:
  interval: 1h
  url: https://github.com/kubeflow/manifests
  ref:
    branch: master
    tag: v1.8.1