package com.unbxd.field.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;

import java.util.Map;

@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Attribute {
    private String fieldName;
    private String fieldType;
    private String searchable;
    private String spellcheck;
    private String multiValued;
    private String autocomplete;
    private String available;
    private Integer version;
    private String variant;
    private String id;
    private Integer depth;
    private boolean autoGenerated;
    private Map<String,String> parent;
    private String alias;
}
