#mongodb-maindb-service-stateful.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless-service
  labels:
    name: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongodb
---
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: apps/v1
{{- else -}}
apiVersion: apps/v1beta1
{{- end }}
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      role: mongodb # has to match .spec.template.metadata.labels
  serviceName: mongodb-headless-service
  replicas: 1
  template:
    metadata:
      labels:
        role: mongodb
        tier: maindb
        replicaset: Shard1
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb-container
          image: mongo:3.4
          command:
            - "mongod"
            - "--port"
            - "27017"
            - "--bind_ip"
            - "0.0.0.0"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 27017
