apiVersion: v1
kind: Service
metadata:
  name: {{ include "skipper.fullname" . }}
  labels:
    {{- include "skipper.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8338
      protocol: TCP
      name: http
  selector:
    {{- include "skipper.selectorLabels" . | nindent 4 }}
