apiVersion: batch/v1
kind: Job
metadata:
  name: "test-{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": test
spec:
  ttlSecondsAfterFinished: 100
  template:
   spec:
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    restartPolicy: Never
    containers:
     - name: test-{{ .Release.Name }}
       image: "{{ .Values.image.repository }}:test-{{ .Values.image.tag | default .Chart.AppVersion }}"
       imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
       args: ["run", "skipper.postman-collection.json", "-e", "local.postman_environment.json"]
