# this config is for prod use
apiVersion: batch/v1
kind: Job
metadata:
  name: variants-migration
  namespace: ss
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: variants-migration
          image: 012629307706.dkr.ecr.us-east-1.amazonaws.com/skipper:variants-migration
          imagePullPolicy: Always
          env:
            - name: gimli_url
              value: "http://gimli.prod.ap-southeast-2.infra"
            - name: skipper_url
              value: "http://skipper.ss"
            - name: brewer_url
              value: "http://brewer.prod.ap-southeast-2.infra"
            - name: admin_cookie
              value: "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjpudWxsLCJleHBpcnkiOiIyMDIxLTEwLTExIDE0OjE5OjMwIFVUQyIsImVtYWlsIjoieW9nZW5kcmEucEB1bmJ4ZC5jb20iLCJyZWdpb25zIjp7InVzIjp7InJlZl91c2VyX2lkIjo4MDg0OX0sInNnIjp7InJlZl91c2VyX2lkIjo0MDR9LCJ1ayI6eyJyZWZfdXNlcl9pZCI6MzcwfSwiYXUiOnsicmVmX3VzZXJfaWQiOjM4NX0sInVzX2djcCI6eyJyZWZfdXNlcl9pZCI6MzgxfX19.oipZB0CvL-8SBCzj3k2-DnDjYYznlFdChgdOX3HjS2w"
            - name: mongo_host
              value: "mongodb://mongodb-shard1-0.mongodb-shard1-headless-service:27017,mongodb-shard1-1.mongodb-shard1-headless-service:27017,mongodb-shard1-2.mongodb-shard1-headless-service:27017/?replicaSet=Shard1"
      restartPolicy: Never