package com.unbxd.skipper.states.model;

public enum ServeStateType {
    CREATE_SITE, CREATE_SITE_CONSOLE, SITE_CREATED, CONSOLE_ERROR,
    PIM_SELECT, PIM_UPLOAD_START, PIM_ERROR, PIM_UPLOAD_COMPLETE, PIM_PROPERTIES_COMPLETE,
    AI_SETUP, MANUAL_SETUP,
    RELEVANCY_JOB_START, RELEVANCY_ERROR_STATE, RELEVANCY_JOB_COMPLETE,
    SETUP_SEARCH, SELECT_TEMPLATE, CONFIGURE_TEMPLATE,
    PLATFORM_SELECT, PLATFORM_UPLOAD, PLATFORM_UPLOAD_COMPLETE, PLATFORM_UPLOAD_ERROR,

    API_SELECT, API_UPLOAD, API_UPLOAD_COMPLETE, API_UPLOAD_ERROR,

    FILE_FEED_SELECT, FILE_FEED_UPLOAD,  FILE_FEED_UPLOAD_COMPLETE, FILE_FEED_UPLOAD_ERROR,
    INDEXING_STATE,

    DIMENSION_UPDATE, DIMENSION_MAPPING_START
 }
