# Default values for skipper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 012629307706.dkr.ecr.us-east-1.amazonaws.com/skipper
  pullPolicy: Always
  tag: "v1.17"

postUpgradeImage:
  repository: 012629307706.dkr.ecr.us-east-1.amazonaws.com/skipper-post-upgrade
  pullPolicy: Always
  tag: "v1.17"

datacenter:
  json: {"data":{"regions":[{"id":"us-gcp","name":"us","lat_long":"37.0902N,95.7129W","type":"GCP","skipperEndPoint":"https://console-g-nam.unbxd.io"},{"id":"us","name":"us","lat_long":"37.0902N,95.7129W","type":"AWS","skipperEndPoint":"https://console-nam.unbxd.io"},{"id":"sg","name":"sg","lat_long":"1.3521N,103.8198E","type":"AWS","skipperEndPoint":"https://console-apac.unbxd.io"},{"id":"uk","name":"uk","lat_long":"55.3781N,3.4360W","type":"AWS","skipperEndPoint":"https://console-uk.unbxd.io"},{"id":"au","name":"au","lat_long":"25.2744S,133.7751E","type":"AWS","skipperEndPoint":"https://console-anz.unbxd.io"}]}}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

selectorLabels:
  app: skipper
  env: ssprod
  region: us-east-1
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000


service:
  type: NodePort
  port: 80
  annotations: {}
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
     cpu: 900m
     memory: 2048Mi
  requests:
     cpu: 600m
     memory: 2048Mi

AWS_ACCESS_KEY_ID: "QUtJQVFGNEdENkU1SVVRVlJTVVk="
AWS_SECRET_ACCESS_KEY: "M0dmdVJGc0ZGczJ5SHJSYnNxbmJQMGlWaDdnWXdzWVdiM1dVRGxYcQ=="

envVars:
  - name: "SYSTEM_OPTS"
    value: "-Dssobase.url=http://console-proxy.prod.use-1d.infra/v1/ -Dconsole.url=http://console-proxy.prod.use-1d.infra/ -Dpim.url=https://pim.unbxd.io/  -Dmongo=mongodb://mongodb-shard1-0.mongodb-shard1-headless-service:27017,mongodb-shard1-1.mongodb-shard1-headless-service:27017,mongodb-shard1-2.mongodb-shard1-headless-service:27017/?replicaSet=Shard1 -Dpim-searchapp.url=https://search-pimapps.unbxd.io/setup/  -Dfeed.url=http://wingman-feed.prod.use-1d.infra/ -Dfeed.healthcheck=ping  -Dgimli.url=http://gimli.prod.use-1d.infra/ -Dgimli.healthcheck=api/getHealthStatus.do -Drelevancy.url=http://relevance-workflow:80 -Drelevancy.healthcheck=/v1.0/relevancy/live -Dconsole-backend.healthcheck=/app/ping -Dconsole-backend.url=https://console-nam.unbxd.io -Dsearch.url=http://brewer.prod.use-1d.infra/ -Dsearch.healthcheck=monitor -Ddomain.name=skipper.ssprod.us-east-1.infra -Dasterix.url=http://asterix.prod.use-1d.infra/ -Dasterix.healthcheck=monitor -DHagrid.url=http://hagrid.prod.use-1d.infra/  -DHagrid.healthcheck=api/monitor -Dpim.internal.url=http://paprika.pimento.us-west-1.infra/ -Dpim.internal.healthcheck=api/monitor -Dmozart.url=http://mozart.prod.use-1d.infra/ -Dmozart.healthcheck=ping -Dregion=us -Daws-region=us-east-1 -DAWS_DEFAULT_REGION=us-east-1 -Dconsumer.url=http://toucan.ssprod.us-east-1.infra/ -Dconsumer.healthcheck=monitor -Dviper.url=https://search-pimapps.unbxd.io/ -Dviper.healthcheck=/ -Dfacet.authKey=\"Basic Ym90QHVuYnhkLmNvbToyMHVuOHhkMTA=\" -DselfServe.s3Bucket=ss-unbxd-us-east-1 -DautosuggestThreshold=0.0f"
  - name: "JAVA_OPTS"
    value: "-XX:ParallelGCThreads=5 -XX:ConcGCThreads=2 -XX:+PrintGCDetails -XX:+UseContainerSupport -XX:+UnlockExperimentalVMOptions  -XshowSettings:vm -XX:MaxRAMPercentage=70.0"
  - name: "AWS_DEFAULT_REGION"
    value: "us-east-1"

mongo:
 connectionString: "mongodb://mongos-headless-service.search:27017"
nodeSelector: {}

tolerations: []

affinity: {}
