package com.unbxd.pim.event.model;

public enum PimEventType {
    START_NODE,IMPORT,APPLY_FILTERS,BULK_EDIT,ADD_CATEGORY,ADD_TO_PRODUCT_GROUP,CREATE_PIM_TASK,CREATE_CATALOG,
    CERTIFY_TO_NETWORK,FILTER_NETWORK_PRODUCTS,RUN_READINESS_CHECK,NOTIFICATION_NODE,EXPORT
}
