{{- if .Values.envoy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.envoy.configMapName }}
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 1000
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              http_filters:
              - name: envoy.filters.http.ext_authz
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                  http_service:
                    path_prefix: "/v1/auth/sso-ambassador/"
                    server_uri:
                      uri: http://console-proxy.console
                      cluster: ext-authz
                      timeout: 0.50s
                    authorization_request:
                      allowed_headers:
                        patterns: [{exact: x-xsrf-token},{exact: Cookie},{exact: cookie}]
                    authorization_response:
                      allowed_upstream_headers_to_append:
                        patterns: [{exact: x-xsrf-token-set},{exact: Cookie},{exact: cookie}]

              - name: envoy.filters.http.router
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains:
                  - "*"
                  response_headers_to_add: [{"header":{"key":x-xsrf-token-set,"value":"%REQ(x-xsrf-token-set)%"},"append":false}]
                  routes:
                  - name: falcon
                    match:
                      safe_regex:
                        google_re2: {}
                        regex: ^\/skipper\/site\/.*\/dp\/.*
                    route:
                      regex_rewrite:
                        pattern:
                          google_re2: {}
                          regex: "\\/skipper\\/(.*)"
                        substitution: /\1
                      cluster: falcon_service
                  - name: toucan_mapping
                    match:
                      safe_regex:
                        google_re2: {}
                        regex: ^\/skipper\/admin\/toucan\/.*
                    route:
                      regex_rewrite:
                        pattern:
                          google_re2: {}
                          regex: \/skipper\/(.*)
                        substitution: /\1
                      cluster: toucan_service
                  - name: ner_related_apis
                    match:
                      safe_regex:
                        google_re2: {}
                        regex: ^\/skipper\/.*\/site\/.*\/ner\/(entityFieldMapping|entityBoost|entities|settings|manageEntities)
                    route:
                      regex_rewrite:
                        pattern:
                          google_re2: {}
                          regex: \/skipper\/(.*)/site\/(.*)/ner\/(.*)
                        substitution: /api/\1/sites/\2/ner/\3
                      cluster: ner_service
                  - name: ner_tags
                    match:
                      safe_regex:
                        google_re2: {}
                        regex: ^\/skipper\/.*\/site\/.*\/ner\/tags
                    route:
                      regex_rewrite:
                        pattern:
                          google_re2: {}
                          regex: \/skipper\/(.*)/site\/(.*)/ner\/tags
                        substitution: /\1/sites/\2/tag
                      cluster: ner_service
                  - name: ner_tags_demo
                    match:
                      safe_regex:
                        google_re2: {}
                        regex: ^\/skipper\/.*\/verticals\/.*\/tag
                    route:
                      regex_rewrite:
                        pattern:
                          google_re2: {}
                          regex: \/skipper\/(.*)\/verticals\/(.*)\/tag
                        substitution: /\1/verticals/\2/tag
                      cluster: ner_service
                  - name: skipper_auth_mapping
                    match:
                      prefix: /skipper/auth/
                    route:
                      regex_rewrite:
                        pattern:
                          google_re2: {}
                          regex: \/skipper\/(.*)
                        substitution: /\1
                      cluster: ext-authz
                  - name: skipper_health_check
                    match:
                      prefix: /skipper/services/healthcheck
                    route:
                      prefix_rewrite: /services/healthcheck
                      cluster: skipper_service
                    typed_per_filter_config:
                      envoy.filters.http.ext_authz:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                        disabled: true
                  - name: skipper
                    match:
                      prefix: "/skipper/"
                    route:
                      cluster: skipper_service

      clusters:
      - name: skipper_service
        connect_timeout: 0.25s
        type: LOGICAL_DNS
        load_assignment:
          cluster_name: skipper_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: skipper.ss
                    port_value: 80
      - name: falcon_service
        connect_timeout: 0.25s
        type: LOGICAL_DNS
        load_assignment:
          cluster_name: falcon_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: falcon.ss
                    port_value: 80
      - name: ext-authz
        connect_timeout: 0.25s
        type: logical_dns
        lb_policy: round_robin
        load_assignment:
          cluster_name: ext-authz
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: console-proxy.console
                    port_value: 80
      - name: toucan_service
        connect_timeout: 0.25s
        type: LOGICAL_DNS
        load_assignment:
          cluster_name: toucan_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: toucan.ss
                    port_value: 80
      - name: ner_service
        connect_timeout: 0.25s
        type: LOGICAL_DNS
        load_assignment:
          cluster_name: ner_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: ner.search
                    port_value: 80
  {{- end }}