apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow
  namespace: devops
spec:
  interval: 10m
  targetNamespace: devops
  sourceRef:
    kind: GitRepository
    name: kubeflow-git-repo
  path: "./example"
  prune: true
  timeout: 1m