apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubeflow
  namespace: devops
spec:
  interval: 30s
  path: "./example"
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests