apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow
  namespace: devops
spec:
  interval: 10m0s
  path: "./example"
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  validation: client