apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Git repositories
  - ../git-repo/nithesh-git-repo.yaml
  - ../git-repo/kubeflow-git-repo.yaml

  # Helm releases
  - ../helm/nginx-helm.yaml

  # Kustomization
  - ../kubeflow-kustomize/kustomization.yaml