apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx
  namespace: devops
spec:
  interval: 1m
  path: ./helm/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  template:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: nginx
        namespace: devops
      spec:
        releaseName: nginx
        chart:
          spec:
            chart: nginx
            sourceRef:
              kind: HelmRepository
              name: stable
        values:  # Optional: specify any values to override in the Helm chart
          key: values.yaml
