apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: skipper
  namespace: devops
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: skipper
  install:
    timeout: 20m
  upgrade:
    timeout: 20m
  interval: 2m
  chart:
    spec:
      chart: ../helm/skipper-master/helm/skipper/
      sourceRef:
        kind: GitRepository
        name: flux
  targetNamespace: devops
